= Test backend project for adding / displaying news items

== REST API

Acceptable request / response  content type is `application/json` only.

On success HTTP status code 200 is returned, otherwise 4XX family code is returned on failure.

News represented as `JSON` with following structure

[source,json]
----
{
  "id": {Long},
  "title": {String}
  "author": {String},
  "content": {String},
  "publishDate": {Date}
}
----


=== URL `/news`

Supported methods::
* `POST` - create news item, return `id` of created item in response body
* `GET` - retrieve all news items as JSON list in response body

=== URL `/news/${id}`

`id` is identifier of news item

Supported methods::
* `GET` - retrieve single news item as JSON in response body

== How to build

. Unzip source archive
. Navigate to `test-dropwizard-ch-src` folder with source code
. Execute commands that will download `Gradle` build tool, run test and create distribution

  gradlew clean test distZip

. Distribution archive is located at `build/distributions/test-dropwizard-ch.zip`

== How to run

. Unzip distribution archive
. Navigate to `test-dropwizard-ch` folder
. Create empty database

  bin/test-dropwizard-ch db migrate main.yml

. Start server

  bin/test-dropwizard-ch server main.yml

. Server can be reached at URL `http://localhost:8080`
